name: PHPStan

on:
  push:
    branches: [ main ]
    paths:
      - '**.php'
      - 'phpstan.neon.dist'

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Environment
        uses: ./.github/workflows/create-environment.yml

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
